# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\rcollaboration\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\".\n\rLoginResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"\x1e\n\rLogoutRequest\x12\r\n\x05token\x18\x01 \x01(\t\"1\n\x0eStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"8\n\x0bPostRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"9\n\nGetRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06params\x18\x03 \x01(\t\"$\n\x08\x44\x61taItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"E\n\x0bGetResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12&\n\x05items\x18\x02 \x03(\x0b\x32\x17.collaboration.DataItem\"@\n\nLLMRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t\"1\n\x0bLLMResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t2\xa2\x02\n\x14\x43ollaborationService\x12\x42\n\x05Login\x12\x1b.collaboration.LoginRequest\x1a\x1c.collaboration.LoginResponse\x12\x45\n\x06Logout\x12\x1c.collaboration.LogoutRequest\x1a\x1d.collaboration.StatusResponse\x12\x41\n\x04Post\x12\x1a.collaboration.PostRequest\x1a\x1d.collaboration.StatusResponse\x12<\n\x03Get\x12\x19.collaboration.GetRequest\x1a\x1a.collaboration.GetResponse2S\n\nLLMService\x12\x45\n\x0cGetLLMAnswer\x12\x19.collaboration.LLMRequest\x1a\x1a.collaboration.LLMResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOGINREQUEST']._serialized_start=32
  _globals['_LOGINREQUEST']._serialized_end=82
  _globals['_LOGINRESPONSE']._serialized_start=84
  _globals['_LOGINRESPONSE']._serialized_end=130
  _globals['_LOGOUTREQUEST']._serialized_start=132
  _globals['_LOGOUTREQUEST']._serialized_end=162
  _globals['_STATUSRESPONSE']._serialized_start=164
  _globals['_STATUSRESPONSE']._serialized_end=213
  _globals['_POSTREQUEST']._serialized_start=215
  _globals['_POSTREQUEST']._serialized_end=271
  _globals['_GETREQUEST']._serialized_start=273
  _globals['_GETREQUEST']._serialized_end=330
  _globals['_DATAITEM']._serialized_start=332
  _globals['_DATAITEM']._serialized_end=368
  _globals['_GETRESPONSE']._serialized_start=370
  _globals['_GETRESPONSE']._serialized_end=439
  _globals['_LLMREQUEST']._serialized_start=441
  _globals['_LLMREQUEST']._serialized_end=505
  _globals['_LLMRESPONSE']._serialized_start=507
  _globals['_LLMRESPONSE']._serialized_end=556
  _globals['_COLLABORATIONSERVICE']._serialized_start=559
  _globals['_COLLABORATIONSERVICE']._serialized_end=849
  _globals['_LLMSERVICE']._serialized_start=851
  _globals['_LLMSERVICE']._serialized_end=934
# @@protoc_insertion_point(module_scope)
